# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubenpod < Formula
  desc "kubenpod does something"
  homepage "https://github.com/ehok/kubenpod"
  version "0.0.4"
  license "apache-2.0"

  on_macos do
    url "https://github.com/ehok/kubenpod/releases/download/v0.0.4/kubenpod_0.0.4_darwin_amd64.tar.gz"
    sha256 "0b2d1f53c59995588791d99b899d7a9d995ee48a1f2845f1e2a9666793d8147f"

    def install
      bin.install "kubenpod"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Kubenpod
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ehok/kubenpod/releases/download/v0.0.4/kubenpod_0.0.4_linux_amd64.tar.gz"
        sha256 "c89d463d96caadfe88317d54863dcb53435f85080db37689780b52e5e0b2211d"

        def install
          bin.install "kubenpod"
        end
      end
    end
  end
end
