# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubenpod < Formula
  desc "kubenpod does something"
  homepage "https://github.com/ehok/kubenpod"
  version "0.0.3"
  license "apache-2.0"

  on_macos do
    url "https://github.com/ehok/kubenpod/releases/download/v0.0.3/kubenpod_0.0.3_darwin_amd64.tar.gz"
    sha256 "b7e8c4fe5371255ce34fe14d5507cd6db68918a78aa4a7642b3b37d1c1807437"

    def install
      bin.install "kubenpod"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Kubenpod
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ehok/kubenpod/releases/download/v0.0.3/kubenpod_0.0.3_linux_amd64.tar.gz"
        sha256 "bb1a14d6d45c0902c21b832a23f428811a2ee490b6efe1ba2c33aa344f12f6be"

        def install
          bin.install "kubenpod"
        end
      end
    end
  end
end
