# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dbac < Formula
  desc "dbac :)"
  homepage "https://github.com/ehok/dbac"
  version "1.1.1"
  license "apache-2.0"

  on_macos do
    url "https://github.com/ehok/dbac/releases/download/v1.1.1/dbac_1.1.1_darwin_amd64.tar.gz"
    sha256 "896b9b3c694ffd19622dc6a04963ff4dcd0aecf46f6570f5f9bb7627a4159f86"

    def install
      bin.install "dbac"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Dbac
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ehok/dbac/releases/download/v1.1.1/dbac_1.1.1_linux_amd64.tar.gz"
        sha256 "7da747bc64e93fc2f6362d2f14161490d14cfb78f9136c7d577da63ac344147d"

        def install
          bin.install "dbac"
        end
      end
    end
  end
end
