# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dbac < Formula
  desc "dbac :)"
  homepage "https://github.com/ehok/dbac"
  version "1.1.4"
  license "apache-2.0"

  on_macos do
    url "https://github.com/ehok/dbac/releases/download/v1.1.4/dbac_1.1.4_darwin_amd64.tar.gz"
    sha256 "cdb035dd9bc6056584faf9764c614952f7a834fae3da53424b523d9c3ecde4b2"

    def install
      bin.install "dbac"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Dbac
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ehok/dbac/releases/download/v1.1.4/dbac_1.1.4_linux_amd64.tar.gz"
        sha256 "08e1c28bbbf40cde71cbea130ba75d78c89c36d747666f9fa877895ad00f1686"

        def install
          bin.install "dbac"
        end
      end
    end
  end
end
