# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dbcli < Formula
  desc "dbcli :)"
  homepage "https://github.com/ehok/dbcli"
  version "1.0.3"
  license "apache-2.0"

  on_macos do
    url "https://github.com/ehok/dbcli/releases/download/v1.0.3/dbcli_1.0.3_darwin_amd64.tar.gz"
    sha256 "a2d2c0c448b1c3c8779c1637abe1d463a064ea2315644bfec92eccae6e5d2f1b"

    def install
      bin.install "dbcli"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Dbcli
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ehok/dbcli/releases/download/v1.0.3/dbcli_1.0.3_linux_amd64.tar.gz"
        sha256 "ce268c346800daf0adac3e62f576a532efc58518e9d16467f7d39550c440dd0d"

        def install
          bin.install "dbcli"
        end
      end
    end
  end
end
