# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubenpod < Formula
  desc "kubenpod does something"
  homepage "https://github.com/ehok/kubenpod"
  version "1.1.1"
  license "apache-2.0"

  on_macos do
    url "https://github.com/ehok/kubenpod/releases/download/v1.1.1/kubenpod_1.1.1_darwin_amd64.tar.gz"
    sha256 "07b14426dda99e7e43db95768c10f5859c73b61aa9232cb1e29cb626d358cb7c"

    def install
      bin.install "kubenpod"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Kubenpod
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ehok/kubenpod/releases/download/v1.1.1/kubenpod_1.1.1_linux_amd64.tar.gz"
        sha256 "0553bf363128e6d0db04fc361bdca0b791b12907bd306e50f0c9abfc8d68621e"

        def install
          bin.install "kubenpod"
        end
      end
    end
  end
end
