# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubenpod < Formula
  desc "kubenpod does something"
  homepage "https://github.com/ehok/kubenpod"
  version "1.1.2"
  license "apache-2.0"

  on_macos do
    url "https://github.com/ehok/kubenpod/releases/download/v1.1.2/kubenpod_1.1.2_darwin_amd64.tar.gz"
    sha256 "e7af23dffcc21948bb090edf14921090d0f6475b971831d8928f72e512cea4e6"

    def install
      bin.install "kubenpod"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Kubenpod
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ehok/kubenpod/releases/download/v1.1.2/kubenpod_1.1.2_linux_amd64.tar.gz"
        sha256 "d252824ac024f58fa318391452075c0f1ce91ebbb79db0f3808e08a391e6eba6"

        def install
          bin.install "kubenpod"
        end
      end
    end
  end
end
